spring:
  datasource:
    url: jdbc:mysql://localhost:3306/centraltechv
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
jwt:
  public:
    key: classpath:public_key
  private:
    key: classpath:private_key