#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web: DEBUG
#        authentication: DEBUG

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/centraltechv
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  public:
    key: classpath:public_key
  private:
    key: classpath:private_key

debug: true